apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
spec:
  ports:
    - port: 5050
      nodePort: 5050
      # targetPort: 5050
  selector:
    app: wordpress
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress-image
        imagePullPolicy: Never
        name: wordpress
        ports:
        - containerPort: 5050
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim

# apiVersion: v1
# kind: Service
# metadata:
#     name: wordpress-service
#     labels:
#         app: wordpress
# spec:
#     selector:
#         app: wordpress
#     type: LoadBalancer
#     ports:
#         - port: 5050
#           name: wordpress
#           targetPort: 5050
#           nodePort: 5050

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#     name: wordpress-deployment
#     labels:
#         app: wordpress
# spec:
#     selector:
#         matchLabels:
#             app: wordpress
#     replicas: 1
#     template:
#         metadata:
#             labels:
#                 app: wordpress
#         spec:
#             containers:
#                 - name: wordpress-container
#                   image: wordpress-image
#                   imagePullPolicy: Never
#                   ports:
#                       - containerPort: 5050
#                         name: wordpress