FROM alpine:latest

#nginx 설치
RUN apk update \
&& apk add --no-cache nginx \
&& adduser -D -g 'www' www \
&& mkdir /www

#보안?
RUN chown -R www:www /var/lib/nginx
RUN chown -R www:www /www

#nginx 설정
COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /www/index.html

#ssl 설정
RUN apk add --no-cache openssl \
&& mkdir -p /etc/nginx/ssl \
&& openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj '/C=KR/ST=Korea/L=Seoul/O=innoaca/OU=42seoul/CN=hpark' -keyout /etc/ssl/server.key -out /etc/ssl/server.crt

#ssh
RUN apk add --no-cache openssh \
&& sed 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' -i /etc/ssh/sshd_config \
&& echo 'root:00' | chpasswd \
&& ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -t rsa \
&& ssh-keygen -f /etc/ssh/ssh_host_dsa_key -N '' -t dsa \
&& echo "Port 30022" >> /etc/ssh/sshd_config \
&& mkdir -p /var/run/sshd


EXPOSE 80 443 30022

COPY start.sh start.sh
CMD sh start.sh